// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnRH77UbtdjUJdZtkIjOUjbwyvLSOGklM',
    appId: '1:1097011694914:web:6598f1311c6b86f24cccdb',
    messagingSenderId: '1097011694914',
    projectId: 'clone-c3dbe',
    authDomain: 'clone-c3dbe.firebaseapp.com',
    storageBucket: 'clone-c3dbe.appspot.com',
    measurementId: 'G-PHRW7MGP92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbWE99Muh5O9hrq6bDRUTeh6uMzEFJM6g',
    appId: '1:1097011694914:android:785ce47671be3ebb4cccdb',
    messagingSenderId: '1097011694914',
    projectId: 'clone-c3dbe',
    storageBucket: 'clone-c3dbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3m-70-uQTG6zYdilQ5Nwv3tQpxSeyWZE',
    appId: '1:1097011694914:ios:d14968d574888e734cccdb',
    messagingSenderId: '1097011694914',
    projectId: 'clone-c3dbe',
    storageBucket: 'clone-c3dbe.appspot.com',
    iosClientId: '1097011694914-c65cfp71sflt68uaa1ub8j968gs3529t.apps.googleusercontent.com',
    iosBundleId: 'in.bookany.usersApp',
  );
}
